name: Deploy to Dev
on:
  push:
    branches:
    - main

env:
  ENVIRONMENT: dev

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::817806684191:role/github-actions-service-role
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        role-duration-seconds: 1200
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Display path
      run: | 
        echo $PATH

    - name: Install git-crypt
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install git-crypt
    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      git-crypt unlock ../git-crypt-key
   
    - name: Generate jar
      run: |
        mvn package -Pproduction

    - name: Upload jar to s3
      run: |
        aws s3 cp ./target/flowcrmtutorial-1.0-SNAPSHOT.jar s3://sweng-894-capstone-website/target/flowcrmtutorial-1.0-SNAPSHOT.jar

    - name: Create EB version
      run: |
        aws elasticbeanstalk create-application-version --application-name luni --version-label luni-dev.${{ github.run_number }} --source-bundle S3Bucket=sweng-894-capstone-website,S3Key=target/flowcrmtutorial-1.0-SNAPSHOT.jar

    - name: Deploy new version
      run: |
        aws elasticbeanstalk update-environment --application-name luni --environment-name Luni-env --version-label luni-dev.${{ github.run_number }}


